# Generated by Django 4.2.27 on 2026-01-05 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('partner_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maternity_leave_start', models.DateField(blank=True, null=True)),
                ('maternity_leave_end', models.DateField(blank=True, null=True)),
                ('expected_childcare_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('savings_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
