# Generated by Django 4.2.27 on 2026-01-05 18:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expected_childcare_cost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='savings_goal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='child_age_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR (€)'), ('GBP', 'GBP (£)')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='life_stage',
            field=models.CharField(choices=[('EXPECTING', 'Expecting (pregnant)'), ('EARLY', 'Early parenthood (0–2 years)'), ('PLANNING', 'Planning to try')], default='EXPECTING', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_goal_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='partner_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
